openapi: '3.0.2'
info:
  title: 空き家で Go の URL 一覧
  version: '1.0'

paths:
  /:
    $ref: './paths/root/GET.yml'
  /top:
    $ref: './paths/top/GET.yml'
  /index:
    $ref: './paths/index/GET.yml'
  /signup:
    $ref: './paths/signup/POST.yml'
  /login:
    $ref: './paths/login/GET.yml'
  /authenticate:
    $ref: './paths/authenticate/POST.yml'
  /logout:
    $ref: './paths/logout/DELETE.yml'
  /post/new:
    $ref: './paths/post_new/GET.yml'
  /post/save:
    $ref: './paths/post_save/POST.yml'
  /post/edit:
    $ref: './paths/post_edit/GET.yml'
  /post/update:
    $ref: './paths/post_update/PUT.yml'
  /post/delete:
    $ref: './paths/post_delete/DELETE.yml'

components:
  schemas:
    Post:
      $ref: './components/schemas/Post.yml'
    PostResponse:
      $ref: './components/schemas/PostResponse.yml'
